  - alias: 'Auto Renew SSL Cert'
    trigger:
      platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 29
    action:
      service: shell_command.renew_ssl

  - alias: 'Walkway Motion Notify'
    trigger:
      platform: state
      entity_id: sensor.walkway_motion_detected
      from: 'False'
      to: 'True'
    action:
      service: notify.ios_philips_iphone
      data:
        title: "Motion on Walkway"
        message: "Detected motion on walkway"
        data:
          push:
            category: camera
          entity_id:  camera.walkway

  - alias: 'Walkway Motion Floodlights'
    trigger:
      platform: state
      entity_id: sensor.walkway_motion_detected
      from: 'False'
      to: 'True'
    action:
      - service: switch.turn_on
        entity_id: "switch.switch_6"
      - delay: 2:00
      - service: switch.turn_off
        entity_id: "switch.switch_6"

  - alias: "Barn Lights On 30 Minutes before Sunset"
    trigger:
      platform: sun
      event: sunset
      offset: "-00:30:00"
    action:
      service: scene.turn_on
      entity_id: scene.barnlights_on


  - alias: "Barn Lights Off 30 Minutes after Sunrise"
    trigger:
      platform: sun
      event: sunrise
      offset: "+00:30:00"
    action:
      service: scene.turn_on
      entity_id: scene.barnlights_off

  - alias: "Bedroom Hallway On at 7AM"
    trigger:
      platform: time
      at: '07:00:00'
    action:
        service: switch.turn_on
        entity_id: light.bedroom_hallway

  - alias: "Laundry Closet Light On With Motion"
    trigger:
      platform: state
      entity_id: binary_sensor.laundry_closet_motion
      to: 'on'
    action:
    - service: switch.turn_on
      entity_id: "switch.laundry"

  - alias: "Laundry Closet Light Off"
    trigger:
      platform: state
      entity_id: binary_sensor.laundry_closet_motion
      to: 'off'
    action:
    - service: switch.turn_off
      entity_id: "switch.laundry"

