homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 200
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 300

# TODO uncomment
#recorder:
#  purge_keep_days: 14
#  db_url: mysql://hassuser:hass@localhost/hass_db?charset=utf8

logger:
  default: info
  logs:
    homeassistant.components.media_player: debug
    homeassistant.components.tts: debug

cloud:

#  alexa:
#
#    filter:
#      include_entities:
#        - light.level_7
#    entity_config:
#      light.level_7:
#        name: Island
#        description: Island Light

tts:
  - platform: google_translate
    service_name: google_say

ios:

hue:
  bridges:
    - host: 10.0.1.2

# Enables the frontend
frontend:

lovelace:
  mode: yaml

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: liberty
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

#history_graph:
#  gr1:
#    name: Liberty Graph
#    entities:
#      - sensor.liberty_motion_detected
#      - switch.switch_11
#      - light.level_14
#    hours_to_show: 240
#    refresh: 60

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

binary_sensor:
  - platform: mqtt
    name: "Office Motion"
    state_topic: "smartthings/Office Motion/motion"
    payload_on: "active"
    payload_off: "inactive"
    device_class: "motion"

  - platform: mqtt
    name: "Laundry Closet Motion"
    state_topic: "smartthings/Laundry/motion"
    payload_on: "active"
    payload_off: "inactive"
    device_class: "motion"

  - platform: mqtt
    name: "Garage Motion"
    state_topic: "smartthings/Garage/motion"
    payload_on: "active"
    payload_off: "inactive"
    device_class: "motion"

  - platform: mqtt
    name: "Master Bedroom Motion"
    state_topic: "smartthings/Master Bedroom/motion"
    payload_on: "active"
    payload_off: "inactive"
    device_class: "motion"

  - platform: mqtt
    name: "Mechanical Room Motion"
    state_topic: "smartthings/Mechanical Room/motion"
    payload_on: "active"
    payload_off: "inactive"
    device_class: "motion"

sensor:
  - platform: mqtt
    name: "Laundry Closet Temperature"
    state_topic: "smartthings/Laundry/temperature"
    unit_of_measurement: '°F'
    device_class: "temperature"

  - platform: mqtt
    name: "Master Bedroom Temperature"
    state_topic: "smartthings/Master Bedroom/temperature"
    unit_of_measurement: '°F'
    device_class: "temperature"

  - platform: mqtt
    name: "Office Temperature"
    state_topic: "smartthings/Office Motion/temperature"
    unit_of_measurement: '°F'
    device_class: "temperature"

  - platform: mqtt
    name: "Garage Temperature"
    state_topic: "smartthings/Garage/temperature"
    unit_of_measurement: '°F'
    device_class: "temperature"

  - platform: mqtt
    name: "Mechanical Room Temperature"
    state_topic: "smartthings/Mechanical Room/temperature"
    unit_of_measurement: '°F'
    device_class: "temperature"

  - platform: mqtt
    name: "Laundry Closet Battery"
    state_topic: "smartthings/Laundry/battery"
    unit_of_measurement: '%'
    device_class: "battery"

  - platform: mqtt
    name: "Master Bedroom Battery"
    state_topic: "smartthings/Master Bedroom/battery"
    unit_of_measurement: '%'
    device_class: "battery"

  - platform: mqtt
    name: "Office Battery"
    state_topic: "smartthings/Office Motion/battery"
    unit_of_measurement: '%'
    device_class: "battery"

  - platform: mqtt
    name: "Garage Battery"
    state_topic: "smartthings/Garage/battery"
    unit_of_measurement: '%'
    device_class: "battery"

  - platform: mqtt
    name: "Mechanical Room Battery"
    state_topic: "smartthings/Mechanical Room/battery"
    unit_of_measurement: '%'
    device_class: "battery"


  - platform: template
    sensors:
      secure_house:
        friendly_name: "House Secure"
        value_template: >-
          {% if is_state("cover.garage_door_opener", "closed") and
                is_state("lock.front_door","locked") and
                is_state("lock.garage_foyer_door","locked") -%}
            secure
          {%- else -%}
            insecure
          {%- endif %}
      secure_office:
        friendly_name: "Office Secure"
        value_template: >-
          {% if is_state("lock.garage_office_door","locked") -%}
            secure
          {%- else -%}
            insecure
          {%- endif %}
      motion_walkway:
        friendly_name: "Walkway Motion"
        value_template: >-
          false
      motion_driveway:
        friendly_name: "Driveway Motion"
        value_template: >-
          false
      motion_backyard:
        friendly_name: "Backyard Motion"
        value_template: >-
          false
      gate:
        friendly_name: "Gate"
        value_template: >-
          closed

  - platform: darksky
    api_key: !secret darksky_key
    monitored_conditions:
      - summary
      - icon
      - temperature
      - apparent_temperature
      - temperature_min
      - temperature_max
      - pressure
      - humidity
      - visibility
      - wind_speed
      - wind_bearing
      - precip_probability
      - precip_intensity
      - precip_type

  - platform: amcrest

# Weather prediction
  - platform: yr

# Cert monitor:
#  - platform: command_line
#    name: SSL Cert Expiry
#    unit_of_measurement: days
#    scan_interval: 10800
#    command: !secret cert_check_command

#shell_command:
#  renew_ssl: ~/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 30000
 
ffmpeg:
  ffmpeg_bin: /usr/local/bin/ffmpeg

stream:

amcrest:
  - host: 10.0.1.203
    name: livingroom
    username: !secret amcrest_username
    password: !secret amcrest_password
    sensors:
      - motion_detector
  - host: 10.0.1.205
    name: garage
    username: !secret amcrest_username
    password: !secret amcrest_password
    sensors:
      - motion_detector
  - host: 10.0.1.207
    name: walkway
    username: !secret amcrest_username
    password: !secret amcrest_password
    sensors:
      - motion_detector
  - host: 10.0.1.208
    name: backyard
    username: !secret amcrest_username
    password: !secret amcrest_password
    sensors:
      - motion_detector
  - host: 10.0.1.210
    name: driveway
    username: !secret amcrest_username
    password: !secret amcrest_password
    sensors:
      - motion_detector

camera:
#  - platform: ffmpeg
#    input: rtsp://admin:acrules76@10.0.1.207:554/cam/realmonitor?channel=1&subtype=1
#    name: Walkway2

#cover:
#  - platform: myq
#    username: !secret myq_username
#    password: !secret myq_password
#    type: liftmaster

#climate:
#  - platform: honeywell
#    region: us
#    username: !secret honeywell_username 
#    password: !secret honeywell_password
#    scan_interval: 1200

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant-1
  keepalive: 60

scene: !include_dir_list scenes
